#!/usr/bin/env perl
# OpenOSX deep-rename: PureDarwin -> OpenOSX, replayable after upstream syncs.
#
# Pass 1 rewrites file CONTENTS; pass 2 renames FILES/DIRS by applying the
# exact same substitution rules to each tracked path — so on-disk names always
# match what pass 1 turned the references into.
#
# The -D rules exist because CMake/meson define flags glue "-D" onto the macro
# name, defeating the \b word-boundary rules (found the hard way: ld64 built
# without TAPI because -DPUREDARWIN_LIBTAPI_* was not renamed while its
# consumer was).
#
# Guards (lines NEVER touched): copyright/attribution lines, live external
# references (github PureDarwin org, puredarwin.org, discord). Excluded paths:
# license files (incl. PUREDARWIN-LICENSES.md), vendored subtrees
# (tools/xnu-loader, tools/kc-tools), this script.
#
# Known intentionally-unrenamed internal identifiers (glued camelCase, fully
# consistent on both definition and use sites): mkPureDarwinBuild,
# puredarwinArch, puredarwinSource, and file basenames like
# puredarwininput_drv / virgl_puredarwin_* / *_PureDarwin.c / xf86drmPuredarwin.
use strict; use warnings;
use File::Path qw(make_path);
use File::Basename qw(dirname);

sub excluded {
    my ($f) = @_;
    return 1 if $f =~ m{^(PUREDARWIN_LICENSE\.txt|APPLE_LICENSE\.txt|APPLE_DRIVER_LICENSE\.txt)$};
    return 1 if $f =~ m{PUREDARWIN-LICENSES\.md$};
    return 1 if $f =~ m{^tools/(xnu-loader|kc-tools)/};
    return 1 if $f =~ m{^docs/PUREDARWIN_ATTRIBUTION\.md$};
    # All of docs/ is prose we author deliberately, and much of it states facts
    # about upstream: "PureDarwin PR #171", "PureDarwin/xnu-loader", "Apple told
    # PureDarwin ...". A blanket rename turns those into falsehoods. If a doc
    # should say OpenOSX, write OpenOSX when authoring it.
    return 1 if $f =~ m{^docs/};
    return 1 if $f =~ m{rename-openosx.*\.pl$};
    # flake.lock is generated by nix and records upstream input origins as
    # JSON fields ("owner": "PureDarwin"), invisible to the github: URL
    # guard. Rewriting it points inputs at a nonexistent org and churns the
    # flake hash on every re-lock. Nix owns this file.
    return 1 if $f eq 'flake.lock';
    return 0;
}

sub apply_rules {
    my ($s) = @_;
    $s =~ s/-DPUREDARWIN_/-DOPENOSX_/g;
    # fastfetch generates FASTFETCH_DATATEXT_LOGO_<NAME> from the ascii logo
    # FILENAME, so renaming the file desyncs this reference. Targeted rather
    # than a blanket /_PUREDARWIN/ rule: the other underscore-glued names are
    # self-consistent header guards, and rewriting them would churn rebuilds.
    $s =~ s/DATATEXT_LOGO_PUREDARWIN/DATATEXT_LOGO_OPENOSX/g;
    # Same hazard: meson derives WLR_HAS_<BACKEND>_BACKEND from the backend
    # option name ('openosx-backend' after the rename), so the hand-written
    # #if in backend.c must follow. Glued between underscores, so the \b
    # rules cannot see it.
    $s =~ s/WLR_HAS_PUREDARWIN_BACKEND/WLR_HAS_OPENOSX_BACKEND/g;
    $s =~ s/-DPUREDARWIN\b/-DOPENOSX/g;
    $s =~ s/__PUREDARWIN__/__OPENOSX__/g;
    $s =~ s/org\.puredarwin\./org.openosx./g;
    $s =~ s/\bPUREDARWIN_(?!LICENSE)/OPENOSX_/g;
    $s =~ s/\bPUREDARWIN\b/OPENOSX/g;
    $s =~ s/puredarwin-/openosx-/g;
    $s =~ s/\bpuredarwin\.img\b/openosx.img/g;
    $s =~ s/\bPureDarwin\b/OpenOSX/g;
    $s =~ s/\bpuredarwin\b/openosx/g;
    return $s;
}

# ---- Pass 1: contents ----
my @files = split /\n/, `git ls-files`;
my $changed = 0;
for my $f (@files) {
    next if excluded($f);
    next unless -f $f;
    next if -B $f;  # skip binary files
    open my $in, "<", $f or next;
    my @lines = <$in>; close $in;
    my $dirty = 0;
    for (@lines) {
        next if /Copyright|\x{00A9}|APPLE_LICENSE_HEADER|Portions\s+of/i;
        # Attribution and credit prose. "authored by the PureDarwin developers"
        # carries no Copyright keyword, so the guard above misses it and the
        # rename silently reassigns authorship of other people's work - which
        # is precisely what PUREDARWIN_LICENSE.txt requires us not to do, and
        # what happened in commit 0a93dcfb before this guard existed.
        next if /authored by|successor to|grateful|ATTRIBUTION/i;
        next if /PureDarwin (?:developers|project|license)/i;
        next if m{github(\.com)?[:/]PureDarwin|puredarwin\.org|discord};
        my $before = $_;
        $_ = apply_rules($_);
        $dirty ||= ($before ne $_);
    }
    if ($dirty) {
        open my $out, ">", $f or die "write $f: $!";
        print $out @lines; close $out;
        $changed++;
    }
}
print "contents: rewrote $changed files\n";

# ---- Pass 2: paths (same rules => consistent with rewritten references) ----
my $moved = 0;
for my $f (split /\n/, `git ls-files`) {
    next if excluded($f);
    my $new = apply_rules($f);
    next if $new eq $f;
    make_path(dirname($new));
    system("git", "mv", $f, $new) == 0 or die "git mv $f -> $new failed";
    $moved++;
    print "moved: $f -> $new\n";
}
print "paths: moved $moved files\n";
